### PR TITLE
Fix 404 and 502 errors

### LINKED ISSUE #94: Boyar needs to have 404 page
Whatever path is requested, it will be returned with a default page (unless it's a proxy).

### PR DESCRIPTION
**Pull request by netoneko**
Returns JSON response to 404 and 502 errors.

Fixes the regression when the response is always 200 no matter what.

Fixes #94

### CODE REVIEW

**Comment by electricmonk** [comment]
@netoneko build fails... can you please check?

**Comment by netoneko** [comment]
@electricmonk I reran it again, regular flakiness.

**Comment by electricmonk** [comment]
still red here
why is it flaky?

**Comment by netoneko** [comment]
It's flaky because Docker on circleci isn't in it best shape. But it has nothing to with the PR at hand.

**Pull request merged**
